[versions]
activity-version = "1.12.2"
coroutines-version = "1.10.2"
datastore-version = "1.2.0"
deprecated-navigation-version = "2.9.6"
kotlin-version = "2.2.21"
lifecycle-version = "2.10.0"
mockk-version = "1.14.6"
navigation-version = "1.0.0"
serialization = "1.8.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-version" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-version" }
android-gradle = "com.android.tools.build:gradle:8.13.1"
annotation = "androidx.annotation:annotation:1.9.1"
appauth = "net.openid:appauth:0.11.1"
appcompat = "androidx.appcompat:appcompat:1.7.1"
collections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"
compose-animation = { module = "androidx.compose.animation:animation-core" }
compose-bom = "androidx.compose:compose-bom:2025.12.00"
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundationLayout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiGeometry = { module = "androidx.compose.ui:ui-geometry" }
compose-uiGraphics = { module = "androidx.compose.ui:ui-graphics" }
compose-uiTest = { module = "androidx.compose.ui:ui-test" }
compose-uiText = { module = "androidx.compose.ui:ui-text" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-uiUnit = { module = "androidx.compose.ui:ui-unit" }
constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.1.1"
core = "androidx.core:core-ktx:1.17.0"
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-version" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-version" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore-version" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore-version" }
deprecated-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "deprecated-navigation-version" }
hamcrest = "org.hamcrest:hamcrest:3.0"
junit5-api = "org.junit.jupiter:junit-jupiter-api:5.14.1"
junit5-test = "de.mannodermaus.junit5:android-test-core:1.9.0"
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin-version" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin-version" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle-version" }
lifecycle-extensions = "androidx.lifecycle:lifecycle-extensions:2.2.0"
lifecycle-runtimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-version" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-version" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk-version" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk-version" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk-version" }
navigation-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation-version" }
navigation-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation-version" }
play-auth = "com.google.android.gms:play-services-auth:21.4.0"
preference = "androidx.preference:preference-ktx:1.2.1"
protobuf-javalite = "com.google.protobuf:protobuf-javalite:4.33.2"
telephoto-zoomable = "me.saket.telephoto:zoomable:0.18.0"

[plugins]
dependencyAnalysis = "com.autonomousapps.dependency-analysis:3.5.1"
ktlint = "org.jlleitschuh.gradle.ktlint:14.0.1"
# javaResolver = "org.gradle.toolchains.foojay-resolver-convention:1.0.0"
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }
kotlin-gradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
